Description: Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.Disable-ShowDesktopOnWallpaperClick-settings-profile
MinimumVersion: "2.3"

Input:
  NAME: "Disable Click on Wallpaper"
  IDENTIFIER: com.apple.WindowManager
  ORGANIZATION: Apple
  PROFILE_CATEGORY: System Settings
  PROFILE_TEMPLATE: Profile-1-group.xml
  PROFILE_NAME: "%NAME%"
  PROFILE_PAYLOAD: com.apple.WindowManager.plist
  PROFILE_DESCRIPTION: Disables showing Desktop on Wallpaper Click.
  USERS_GROUP_NAME: "%NAME% users"
  PROFILE_GROUP_TEMPLATE: SmartGroup-users.xml
  REPLACE_PROFILE: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"


  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%PROFILE_GROUP_TEMPLATE%"
      computergroup_name: "%USERS_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      profile_computergroup: "%USERS_GROUP_NAME%"
      replace_profile: "%REPLACE_PROFILE%"
