#!/bin/zsh
# shellcheck shell=bash

### Install Mathematica License
umask 002

license_server="$4"
license_string="$5"
license_type="$6"

host=$(hostname)

mathpass_fileloc="/Library/Mathematica/Licensing/mathpass"
mkdir -p "$(dirname $mathpass_fileloc)"

if [[ -f "$mathpass_fileloc" ]]; then
    mv "$mathpass_fileloc" "$mathpass_fileloc.bak"
fi

if [[ "$license_type" == "Floating" ]]; then
    ## Floating license type

    # Create the LICENSE_FILE
    echo '!'"$license_server" | tee "$mathpass_fileloc"
elif [[ "$license_type" == "Node" ]]; then
    ## Node license type
    # the license string consists of the host name, three long codes, the organisation name and a fixed user name, all separated by tabs.
    #
    # This must be generated by installing the license manually on a single device, and then reading the contents of 
    # ~/Library/Mathematica/Licensing/mathpass
    #
    # Please remove the hostname from the string as this will be substituted in here
    # so we need something like (but with tabs):
    # "235AAAAAAAAAC8DC        4864E34D7AAAAAAAAE6CAF1910    217AAAAA79      Big Org      BigOrg Employee"

    # note the third number is determined by some hash of the User Name, so this file must be generated using "Mitarbeiter ETH". It also requires a tab after the name.
#    echo "%(*userregistered*)" > "$mathpass_fileloc"
    echo "$host	$license_string	" > "$mathpass_fileloc"
else
    echo "ERROR: incorrect license type entered"
    exit 1
fi
